name: Perms
main: com.akaiha.perms.Perms
version: 0.9
description: Created by Akaiha

commands:
  perms:
    permission: perms.perms
    description: Checks all personal permissions info for a player.